apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          envFrom:
            - secretRef:
                name: ai-validation-secrets
            - configMapRef:
                name: ai-validation-config
