apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solierrr

resources:
  - ../../base/api-java

namePrefix: api-auth-

labels:
  - pairs:
      app: api-auth
      app.kubernetes.io/part-of: solierrr
    includeSelectors: true

images:
  - name: placeholder/placeholder
    newName: SEU_USUARIO_DOCKERHUB/solierrr-api-auth
    newTag: latest

patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: app
